export const TEMAS = [
  {
    id: "atual",
    nome: "Atual",
    variaveis: {
      "--bg-principal": "#76BA5B",
      "--bg-header": "#76BA5B",
      "--bg-footer": "#2D2D2D",
      "--bg-card": "#ffffff",
      "--bg-card-secundario": "#f5f5f5",
      "--bg-menu": "#2D2D1A",
      "--texto-principal": "#2D2D1A",
      "--texto-secundario": "#555555",
      "--texto-header": "#ffffff",
      "--texto-footer": "#ffffff",
      "--cor-primaria": "#228B22",
      "--cor-secundaria": "#b6cd32",
      "--cor-destaque": "#E63946",
      "--cor-botao": "#2D2D2D",
      "--texto-botao": "#ffffff",
      "--borda-card": "transparent",
      "--sombra-card": "0 4px 10px rgba(0,0,0,0.1)",
      "--border-radius-card": "25px",

      "--cor-menu-produtos": "#2e357d",
      "--texto-menu-produtos": "#ffffff",
      "--cor-menu-colecoes": "#F4C95D",
      "--texto-menu-colecoes": "#2D2D1A",
      "--cor-menu-categorias": "#D94A5A",
      "--texto-menu-categorias": "#ffffff",
    },
    preview: {
      fundo: "#76BA5B",
      header: "#2D2D1A",
      card: "#ffffff",
      botao: "#2D2D2D",
      destaque: "#E63946",
      textoPrincipal: "#2D2D1A",
      textoCard: "#555555",
    },
  },

  {
    id: "marrom",
    nome: "Marrom & Bege",
    variaveis: {
      "--bg-principal": "#f5f1eb",
      "--bg-header": "#f5f1eb",
      "--bg-footer": "#2c1f14",
      "--bg-card": "#fff",
      "--bg-card-secundario": "#f0e6d3",
      "--bg-menu": "#2c1f14",
      "--texto-principal": "#2c1f14",
      "--texto-secundario": "#6b4e38",
      "--texto-header": "#2c1f14",
      "--texto-footer": "#f0e6d3",
      "--cor-primaria": "#8B5E3C",
      "--cor-secundaria": "#c49a6c",
      "--cor-destaque": "#b94a2c",
      "--cor-botao": "#2c1f14",
      "--texto-botao": "#f0e6d3",
      "--borda-card": "#e8d5bc",
      "--sombra-card": "0 4px 12px rgba(44,31,20,0.12)",
      "--border-radius-card": "20px",

      "--cor-menu-produtos": "#5A3825",
      "--texto-menu-produtos": "#ffffff",
      "--cor-menu-colecoes": "#D2A679",
      "--texto-menu-colecoes": "#2C1F14",
      "--cor-menu-categorias": "#A9543A",
      "--texto-menu-categorias": "#ffffff",
    },
    preview: {
      fundo: "#f5f1eb",
      header: "#2c1f14",
      card: "#fff",
      botao: "#2c1f14",
      destaque: "#b94a2c",
      textoPrincipal: "#2c1f14",
      textoCard: "#6b4e38",
    },
  },

  {
    id: "claro",
    nome: "Claro",
    variaveis: {
      "--bg-principal": "#f0f4f0",
      "--bg-header": "#fff",
      "--bg-footer": "#1a1a1a",
      "--bg-card": "#fff",
      "--bg-card-secundario": "#f8f8f8",
      "--bg-menu": "#1a1a1a",
      "--texto-principal": "#1a1a1a",
      "--texto-secundario": "#444",
      "--texto-header": "#1a1a1a",
      "--texto-footer": "#fff",
      "--cor-primaria": "#228B22",
      "--cor-secundaria": "#4CAF50",
      "--cor-destaque": "#E63946",
      "--cor-botao": "#228B22",
      "--texto-botao": "#fff",
      "--borda-card": "#e0e0e0",
      "--sombra-card": "0 2px 8px rgba(0,0,0,0.08)",
      "--border-radius-card": "16px",

      "--cor-menu-produtos": "#4969A8",
      "--texto-menu-produtos": "#ffffff",
      "--cor-menu-colecoes": "#D6A84F",
      "--texto-menu-colecoes": "#1A1A1A",
      "--cor-menu-categorias": "#C85C72",
      "--texto-menu-categorias": "#ffffff",
    },
    preview: {
      fundo: "#f0f4f0",
      header: "#fff",
      card: "#fff",
      botao: "#228B22",
      destaque: "#E63946",
      textoPrincipal: "#1a1a1a",
      textoCard: "#444",
    },
  },

  {
    id: "escuro",
    nome: "Escuro",
    variaveis: {
      "--bg-principal": "#121212",
      "--bg-header": "#1e1e1e",
      "--bg-footer": "#0a0a0a",
      "--bg-card": "#242424",
      "--bg-card-secundario": "#2a2a2a",
      "--bg-menu": "#0a0a0a",
      "--texto-principal": "#f0f0f0",
      "--texto-secundario": "#aaaaaa",
      "--texto-header": "#f0f0f0",
      "--texto-footer": "#aaaaaa",
      "--cor-primaria": "#4CAF50",
      "--cor-secundaria": "#81C784",
      "--cor-destaque": "#FF5252",
      "--cor-botao": "#4CAF50",
      "--texto-botao": "#fff",
      "--borda-card": "#333",
      "--sombra-card": "0 4px 12px rgba(0,0,0,0.4)",
      "--border-radius-card": "20px",

      "--cor-menu-produtos": "#6C5AA8",
      "--texto-menu-produtos": "#ffffff",
      "--cor-menu-colecoes": "#D9A441",
      "--texto-menu-colecoes": "#121212",
      "--cor-menu-categorias": "#C95A5A",
      "--texto-menu-categorias": "#ffffff",
    },
    preview: {
      fundo: "#121212",
      header: "#1e1e1e",
      card: "#242424",
      botao: "#4CAF50",
      destaque: "#FF5252",
      textoPrincipal: "#f0f0f0",
      textoCard: "#aaaaaa",
    },
  },

  {
    id: "minimalista",
    nome: "Minimalista",
    variaveis: {
      "--bg-principal": "#fafafa",
      "--bg-header": "#fafafa",
      "--bg-footer": "#333",
      "--bg-card": "#fff",
      "--bg-card-secundario": "#f5f5f5",
      "--bg-menu": "#222",
      "--texto-principal": "#222",
      "--texto-secundario": "#666",
      "--texto-header": "#222",
      "--texto-footer": "#ddd",
      "--cor-primaria": "#555",
      "--cor-secundaria": "#888",
      "--cor-destaque": "#228B22",
      "--cor-botao": "#333",
      "--texto-botao": "#fff",
      "--borda-card": "#eee",
      "--sombra-card": "0 1px 4px rgba(0,0,0,0.06)",
      "--border-radius-card": "12px",

      "--cor-menu-produtos": "#536A82",
      "--texto-menu-produtos": "#ffffff",
      "--cor-menu-colecoes": "#A1845B",
      "--texto-menu-colecoes": "#ffffff",
      "--cor-menu-categorias": "#8C5A64",
      "--texto-menu-categorias": "#ffffff",
    },
    preview: {
      fundo: "#fafafa",
      header: "#fafafa",
      card: "#fff",
      botao: "#333",
      destaque: "#228B22",
      textoPrincipal: "#222",
      textoCard: "#666",
    },
  },

  {
    id: "colorido",
    nome: "Colorido",
    variaveis: {
      "--bg-principal": "#e8f5e9",
      "--bg-header": "#1B5E20",
      "--bg-footer": "#1B5E20",
      "--bg-card": "#fff",
      "--bg-card-secundario": "#f1f8e9",
      "--bg-menu": "#1B5E20",
      "--texto-principal": "#1B5E20",
      "--texto-secundario": "#2E7D32",
      "--texto-header": "#fff",
      "--texto-footer": "#fff",
      "--cor-primaria": "#D32F2F",
      "--cor-secundaria": "#F57C00",
      "--cor-destaque": "#D32F2F",
      "--cor-botao": "#D32F2F",
      "--texto-botao": "#fff",
      "--borda-card": "#c8e6c9",
      "--sombra-card": "0 4px 12px rgba(27,94,32,0.15)",
      "--border-radius-card": "20px",

      "--cor-menu-produtos": "#008C95",
      "--texto-menu-produtos": "#ffffff",
      "--cor-menu-colecoes": "#E58A2B",
      "--texto-menu-colecoes": "#ffffff",
      "--cor-menu-categorias": "#7B4FA3",
      "--texto-menu-categorias": "#ffffff",
    },
    preview: {
      fundo: "#e8f5e9",
      header: "#1B5E20",
      card: "#fff",
      botao: "#D32F2F",
      destaque: "#F57C00",
      textoPrincipal: "#1B5E20",
      textoCard: "#2E7D32",
    },
  },
];

export const TEMA_PADRAO = "atual";

export const CHAVE_LOCALSTORAGE = "lutb-tema";

export function getTemaById(id) {
  return TEMAS.find((t) => t.id === id) || TEMAS[0];
}

export function aplicarTema(tema) {
  if (typeof document === "undefined") return;

  const root = document.documentElement;

  Object.entries(tema.variaveis).forEach(([chave, valor]) => {
    root.style.setProperty(chave, valor);
  });
}