export const TEMAS = [
  {
    id: "atual",
    nome: "Atual",
    variaveis: {
      "--bg-principal": "#76BA5B",
      "--bg-header": "#76BA5B",
      "--bg-footer": "#2D2D2D",
      "--bg-card": "#ffffff",
      "--bg-card-secundario": "#f5f5f5",
      "--bg-menu": "#2D2D1A",
      "--texto-principal": "#2D2D1A",
      "--texto-secundario": "#555555",
      "--texto-header": "#ffffff",
      "--texto-footer": "#ffffff",
      "--cor-primaria": "#228B22",
      "--cor-secundaria": "#b6cd32",
      "--cor-destaque": "#E63946",
      "--cor-botao": "#2D2D2D",
      "--texto-botao": "#ffffff",
      "--borda-card": "transparent",
      "--sombra-card": "0 4px 10px rgba(0,0,0,0.1)",
      "--border-radius-card": "25px",

      "--cor-menu-produtos": "#2e357d",
      "--texto-menu-produtos": "#ffffff",
      "--cor-menu-colecoes": "#F4C95D",
      "--texto-menu-colecoes": "#2D2D1A",
      "--cor-menu-categorias": "#D94A5A",
      "--texto-menu-categorias": "#ffffff",
    },
    preview: {
      fundo: "#76BA5B",
      header: "#2D2D1A",
      card: "#ffffff",
      botao: "#2D2D2D",
      destaque: "#E63946",
      textoPrincipal: "#2D2D1A",
      textoCard: "#555555",
    },
  },

  {
    id: "marrom",
    nome: "Marrom & Bege",
    variaveis: {
      "--bg-principal": "#f5f1eb",
      "--bg-header": "#f5f1eb",
      "--bg-footer": "#2c1f14",
      "--bg-card": "#fff",
      "--bg-card-secundario": "#f0e6d3",
      "--bg-menu": "#2c1f14",
      "--texto-principal": "#2c1f14",
      "--texto-secundario": "#6b4e38",
      "--texto-header": "#2c1f14",
      "--texto-footer": "#f0e6d3",
      "--cor-primaria": "#8B5E3C",
      "--cor-secundaria": "#c49a6c",
      "--cor-destaque": "#b94a2c",
      "--cor-botao": "#2c1f14",
      "--texto-botao": "#f0e6d3",
      "--borda-card": "#e8d5bc",
      "--sombra-card": "0 4px 12px rgba(44,31,20,0.12)",
      "--border-radius-card": "20px",

      "--cor-menu-produtos": "#5A3825",
      "--texto-menu-produtos": "#ffffff",
      "--cor-menu-colecoes": "#D2A679",
      "--texto-menu-colecoes": "#2C1F14",
      "--cor-menu-categorias": "#A9543A",
      "--texto-menu-categorias": "#ffffff",
    },
    preview: {
      fundo: "#f5f1eb",
      header: "#2c1f14",
      card: "#fff",
      botao: "#2c1f14",
      destaque: "#b94a2c",
      textoPrincipal: "#2c1f14",
      textoCard: "#6b4e38",
    },
  },

  {
    id: "claro",
    nome: "Claro",
    variaveis: {
      "--bg-principal": "#FFFFFF",
      "--bg-header": "#FFFFFF",
      "--bg-footer": "#F1F5F2",
      "--bg-card": "#FFFFFF",
      "--bg-card-secundario": "#F8FAF8",
      "--bg-menu": "#F3F6F3",
      "--texto-principal": "#202820",
      "--texto-secundario": "#59635B",
      "--texto-header": "#202820",
      "--texto-footer": "#4B554D",
      "--cor-primaria": "#3FA34D",
      "--cor-secundaria": "#8BCF70",
      "--cor-destaque": "#E84A5F",
      "--cor-botao": "#3FA34D",
      "--texto-botao": "#FFFFFF",
      "--borda-card": "#E1E7E1",
      "--sombra-card": "0 2px 8px rgba(0,0,0,0.08)",
      "--border-radius-card": "16px",

      "--cor-menu-produtos": "#5578B5",
      "--texto-menu-produtos": "#FFFFFF",
      "--cor-menu-colecoes": "#D9B24C",
      "--texto-menu-colecoes": "#202820",
      "--cor-menu-categorias": "#D46378",
      "--texto-menu-categorias": "#FFFFFF",
    },
    preview: {
      fundo: "#FFFFFF",
      header: "#FFFFFF",
      card: "#FFFFFF",
      botao: "#3FA34D",
      destaque: "#E84A5F",
      textoPrincipal: "#202820",
      textoCard: "#59635B",
    },
  },

  {
    id: "escuro",
    nome: "Escuro",
    variaveis: {
      "--bg-principal": "#0F0F14",
      "--bg-header": "#16161F",
      "--bg-footer": "#0B0B10",
      "--bg-card": "#1A1A25",
      "--bg-card-secundario": "#1E1E2A",
      "--bg-menu": "#0B0B10",
      "--texto-principal": "#F9FAFB",
      "--texto-secundario": "#9CA3AF",
      "--texto-header": "#F9FAFB",
      "--texto-footer": "#D1D5DB",
      "--cor-primaria": "#7C3AED",
      "--cor-secundaria": "#A78BFA",
      "--cor-destaque": "#10B981",
      "--cor-botao": "#7C3AED",
      "--texto-botao": "#FFFFFF",
      "--borda-card": "#2D2D3E",
      "--sombra-card": "0 4px 12px rgba(0,0,0,0.4)",
      "--border-radius-card": "14px",

      "--cor-menu-produtos": "#7C3AED",
      "--texto-menu-produtos": "#FFFFFF",
      "--cor-menu-colecoes": "#A78BFA",
      "--texto-menu-colecoes": "#17121F",
      "--cor-menu-categorias": "#10B981",
      "--texto-menu-categorias": "#FFFFFF",
    },
    preview: {
      fundo: "#0F0F14",
      header: "#16161F",
      card: "#1A1A25",
      botao: "#7C3AED",
      destaque: "#10B981",
      textoPrincipal: "#F9FAFB",
      textoCard: "#9CA3AF",
    },
  },

  {
    id: "minimalista",
    nome: "Minimalista",
    variaveis: {
      "--bg-principal": "#F7F7F5",
      "--bg-header": "#FFFFFF",
      "--bg-footer": "#20201E",
      "--bg-card": "#FFFFFF",
      "--bg-card-secundario": "#F0F0ED",
      "--bg-menu": "#2B2B28",
      "--texto-principal": "#20201E",
      "--texto-secundario": "#666661",
      "--texto-header": "#20201E",
      "--texto-footer": "#E8E8E3",
      "--cor-primaria": "#444440",
      "--cor-secundaria": "#8A8A84",
      "--cor-destaque": "#20201E",
      "--cor-botao": "#2B2B28",
      "--texto-botao": "#FFFFFF",
      "--borda-card": "#DDDDD8",
      "--sombra-card": "0 1px 4px rgba(0,0,0,0.06)",
      "--border-radius-card": "12px",

      "--cor-menu-produtos": "#4B4B47",
      "--texto-menu-produtos": "#FFFFFF",
      "--cor-menu-colecoes": "#777770",
      "--texto-menu-colecoes": "#FFFFFF",
      "--cor-menu-categorias": "#5F5F59",
      "--texto-menu-categorias": "#FFFFFF",
    },
    preview: {
      fundo: "#F7F7F5",
      header: "#FFFFFF",
      card: "#FFFFFF",
      botao: "#2B2B28",
      destaque: "#20201E",
      textoPrincipal: "#20201E",
      textoCard: "#666661",
    },
  },

  {
    id: "colorido",
    nome: "Colorido",
    variaveis: {
      "--bg-principal": "#FFF0F6",
      "--bg-header": "#FF4F8B",
      "--bg-footer": "#E83E78",
      "--bg-card": "#FFFFFF",
      "--bg-card-secundario": "#FFE0EB",
      "--bg-menu": "#E83E78",
      "--texto-principal": "#552139",
      "--texto-secundario": "#8A526C",
      "--texto-header": "#FFFFFF",
      "--texto-footer": "#FFFFFF",
      "--cor-primaria": "#00A896",
      "--cor-secundaria": "#FFC857",
      "--cor-destaque": "#FF4F81",
      "--cor-botao": "#00A896",
      "--texto-botao": "#FFFFFF",
      "--borda-card": "#FFC2D8",
      "--sombra-card": "0 4px 12px rgba(27,94,32,0.15)",
      "--border-radius-card": "20px",

      "--cor-menu-produtos": "#00A6A6",
      "--texto-menu-produtos": "#FFFFFF",
      "--cor-menu-colecoes": "#F5A623",
      "--texto-menu-colecoes": "#FFFFFF",
      "--cor-menu-categorias": "#FF70A6",
      "--texto-menu-categorias": "#FFFFFF",
    },
    preview: {
      fundo: "#FFF0F6",
      header: "#FF4F8B",
      card: "#FFFFFF",
      botao: "#00A896",
      destaque: "#FFC857",
      textoPrincipal: "#552139",
      textoCard: "#8A526C",
    },
  },
];

export const TEMA_PADRAO = "atual";

export const CHAVE_LOCALSTORAGE = "lutb-tema";

export function getTemaById(id) {
  return TEMAS.find((t) => t.id === id) || TEMAS[0];
}

export function aplicarTema(tema) {
  if (typeof document === "undefined") return;

  const root = document.documentElement;

  Object.entries(tema.variaveis).forEach(([chave, valor]) => {
    root.style.setProperty(chave, valor);
  });
}